
version: "3.8"

services:
  redis-server:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    restart: always

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/FunBoxAPI
    ports:
      - "8000:8000"
    depends_on:
      - redis-server